
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' data: https:; connect-src 'self' https: data:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline';"
